export const TRANSACTIONS_REQUEST = 'TRANSACTIONS_REQUEST';
export const TRANSACTIONS_SUCCESS = 'TRANSACTIONS_SUCCESS';
export const TRANSACTIONS_FALURE = 'TRANSACTIONS_FALURE';

export const TRANSACTION_DETAILS = 'TRANSACTION_DETAILS';

export const TOGGLE_FILTER = 'TOGGLE_FILTER';
export const SORT_AND_PAGINATE = 'SORT_AND_PAGINATE';
